// Application types
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_TEAM_ID = 'SET_TEAM_ID';
export const REGISTER_USER = 'REGISTER_USER';
export const FORGOT_USER_PASSWORD = 'FORGOT_USER_PASSWORD';
export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD';
export const VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL';
export const REFRESHED_TOKEN = 'REFRESHED_TOKEN';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const REGISTER_FORM = 'REGISTER_FORM';
export const IS_GUEST = 'IS_GUEST';
export const SHOULD_RELOAD_USER = 'SHOULD_RELOAD_USER';
export const TEST_AUTH = 'TEST_AUTH';

export const INDEX_USER = 'INDEX_USER';
export const FILTER_USER ='FILTER_USER';
export const SHOW_USER = 'SHOW_USER';
export const SEARCH_USER = 'SEARCH_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const BLOCK_USER = 'BLOCK_USER';
export const UNBLOCK_USER = 'UNBLOCK_USER';
export const TEST_USER = 'TEST_USER';

export const SET_ACTIVITY_NOTIFICATION = 'SET_ACTIVITY_NOTIFICATION';
export const UNSET_ACTIVITY_NOTIFICATION = 'UNSET_ACTIVITY_NOTIFICATION';
export const ACTIVITY_LOADING = 'ACTIVITY_LOADING';
export const UNSET_ACTIVITY_MESSAGE = 'UNSET_ACTIVITY_MESSAGE';
export const SET_ACTIVITY_MESSAGE = 'SET_ACTIVITY_MESSAGE';


export const INDEX_PROFILE = 'INDEX_PROFILE';
export const FILTER_PROFILE = 'FILTER_PROFILE';
export const SEARCH_PROFILE = 'SEARCH_PROFILE';
export const SHOW_PROFILE = 'SHOW_PROFILE';
export const MY_PROFILE = 'MY_PROFILE';
export const STORE_PROFILE = 'STORE_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const TEST_PROFILE = 'TEST_PROFILE';

export const USER_HELP_MESSAGE = 'USER_HELP_MESSAGE';
export const SAVE_GENDER = 'SAVE_GENDER';
export const SAVE_BOOLEAN_CHOICE = 'SAVE_BOOLEAN_CHOICE';
export const SAVE_FLAG_CHOICE = 'SAVE_FLAG_CHOICE';

export const INDEX_PUSH_NOTIFICATION = 'INDEX_PUSH_NOTIFICATION';
export const STORE_PUSH_NOTIFICATION = 'STORE_PUSH_NOTIFICATION';
export const SHOW_PUSH_NOTIFICATION = 'SHOW_PUSH_NOTIFICATION';
export const MY_PUSH_NOTIFICATION = 'MY_PUSH_NOTIFICATION';
export const EDIT_PUSH_NOTIFICATION = 'EDIT_PUSH_NOTIFICATION';
export const DELETE_PUSH_NOTIFICATION = 'DELETE_PUSH_NOTIFICATION';
export const TEST_PUSH_NOTIFICATION = 'TEST_PUSH_NOTIFICATION';

export const MY_NOTIFICATION = 'MY_NOTIFICATION';

export const INDEX_COMIC = 'INDEX_COMIC';
export const FILTER_COMIC = 'FILTER_COMIC';
export const SEARCH_COMIC = 'SEARCH_COMIC';
export const SHOW_COMIC = 'SHOW_COMIC';
export const STORE_COMIC = 'STORE_COMIC';
export const EDIT_COMIC = 'EDIT_COMIC';
export const DELETE_COMIC = 'DELETE_COMIC';